pasqal-io/qadence

qadence/transpile/block.py, tests/qadence/test_transpile.py
When the krons in a chain of krons where not covering the whole qubit support `chain_single_qubit_ops` was failling
=> [Fix] corner case of `chain_single_qubit_ops`

docs/digital_analog_qc/pulser-basic.md, pyproject.toml, qadence/backends/pulser/backend.py, qadence/backends/pulser/cloud.py, qadence/backends/pulser/config.py, qadence/execution.py
Cloud interface implementation in pulser backend.
=> Cloud interface implementation in pulser backend

qadence/backends/braket/convert_ops.py, tests/backends/test_backends.py
Previously, the cphase gate in braket was ALWAYS initialized with a fixed parameter instead of checking if the underlying expression contains trainable symbols, now its possible
=> [Fix] Braket CPHASE always having fixed parameters

docs/digital_analog_qc/analog-basics.md, docs/digital_analog_qc/pulser-basic.md, docs/tutorials/hamiltonians.md, docs/tutorials/register.md, qadence/analog/interaction.py, qadence/backends/pulser/backend.py, qadence/backends/pulser/config.py, qadence/backends/pulser/pulses.py, qadence/blocks/analog.py, qadence/constructors/hamiltonians.py, qadence/register.py, tests/analog/test_analog_emulation.py, tests/analog/test_pyq_vs_pulser.py, tests/backends/pulser_basic/test_configuration.py, tests/backends/pulser_basic/test_differentiation.py, tests/backends/pulser_basic/test_entanglement.py, tests/backends/pulser_basic/test_pulser_conversion.py, tests/qadence/test_register.py
- Moves the register `spacing` as an argument to the `Register` itself.
- Changes the `spacing` functionality: Instead of multiplying whatever coordinates are in the register with the value of the spacing, it rescales the coordinates so that the distance between the two closest qubits is equal to the spacing (consistent with the spacing argument in the Pulser register).
- Rescaling coordinates from the register can still be done with the method `reg.rescale_coords(scaling: float)` which initializes a new register where all coordinates are multiplied by the scaling value.
BREAKING:
- Some of the arguments from the `Register` methods have been changed so that they are all now `spacing`.
- The default scaling of coordinates in the Pulser backend has been removed so that now a Qadence …
=> [Feature] Add coords scaling and distance calculation directly to Register

docs/digital_analog_qc/semi-local-addressing.md, qadence/analog/parse_analog.py, qadence/backends/pulser/pulses.py, qadence/blocks/analog.py, qadence/operations.py, tests/analog/test_patterns.py
Adds the possibility to turn off the addressing pattern for specific analog operations in the pyqtorch backend.
Currently just throws a warning in the pulser backend. The implementation there is a bit more tricky.
=> [Feature] Allow turning off the semi-local addressing pattern in pyqtorch backend

qadence/constructors/iia.py
Relates to #272 Added `param_prefix` to Identity initialized ansatz. It defaults to an empty string.
=> [Feature] Added param_prefix to IIA

docs/digital_analog_qc/analog-basics.md, docs/digital_analog_qc/analog-qcl.md, docs/digital_analog_qc/pulser-basic.md, docs/qadence/operations.md, examples/draw.py, pyproject.toml, qadence/analog/parse_analog.py, qadence/backend.py, qadence/backends/pulser/pulses.py, qadence/blocks/analog.py, qadence/blocks/utils.py, qadence/draw/utils.py, qadence/mitigations/analog_zne.py, qadence/operations.py, qadence/types.py, tests/analog/test_analog_block.py, tests/analog/test_analog_emulation.py, tests/analog/test_pyq_vs_pulser.py, tests/backends/pulser_basic/test_differentiation.py
I suggest to replace the `wait` alias operation with `AnalogInteraction` to be a bit more formal and explicit about what it does (it evolves the interaction term in the Hamiltonian for a register of interacting qubits).
=> [Refact] Replace alias wait with AnalogInteraction

pyproject.toml, qadence/models/quantum_model.py
Store the noise model as QM class attribute for later retrieval when passed to methods.
=> Store the noise model when passed to sample method.

qadence/blocks/primitive.py, qadence/utils.py, tests/qadence/test_matrices.py
See https://github.com/pasqal-io/qadence/issues/320 for context on eigenvalues change.
Furthermore a recent change to the control blocks made `block_to_tensor` give incorrect results for non-sequential qubit supports, which was not tested.
=> [BugFix] Wrong tensor for control blocks, inefficient eigenvalues

pyproject.toml, qadence/ml_tools/data.py, qadence/ml_tools/optimize_step.py, qadence/ml_tools/train_grad.py
To avoid having to let the user move arbitary (custom) data loader types to the device, we reintroduce the 'device' arg to `optimize_step` which uses `data_to_device` method which supports a variety of qadence-compatible data types.
=> [Refac] Add 'device' to ml_tools optimize_step

qadence/ml_tools/models.py, qadence/ml_tools/saveload.py, qadence/models/quantum_model.py, tests/ml_tools/test_checkpointing.py
When training the same model twice, however on different devices, `train_grad` fails due to the checkpoints differing in devices. This MR adds a "device" suffix to each created checkpoint
=> [Refac] Add device to model checkpoints

qadence/backends/pulser/convert_ops.py
In case the user provides a non-parametric observable, compute it once and reuse it
=> [Performance] Cache non-parametric pulser observable

qadence/backends/horqrux/backend.py
Increase speed of horqrux sampling:
New:
In [3]: %timeit sample(RX(20,'theta'),backend='horqrux')
45.3 ms ± 187 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
Old:
In [2]: %timeit sample(RX(20,'theta'),backend='horqrux')
4.28 s ± 25.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
=> [Performance] Improve horqrux sampling

qadence/states.py, tests/qadence/test_states.py
Adding a `backend` argument to the `product_state` function that results in a native product state representation. 
Closes #370
=> [Refac] Add `backend` argument to `product_state` function

pyproject.toml, qadence/backends/pyqtorch/backend.py, qadence/backends/utils.py, qadence/utils.py
Related to https://github.com/pasqal-io/pyqtorch/pull/204. Avoid inferring batch_size from dicts when tensors are expected
=> [Fix] Handle nested parameter dicts

qadence/ml_tools/saveload.py, qadence/model.py, tests/ml_tools/test_checkpointing.py, tests/qadence/test_quantum_model.py
Fixes #484 
This PR proposes a new method in QuantumModel, `load_params_from_dict()` which allows to load the parameters from a dictionary directly to the current model. There is already a similar method `.from_dict()` but that one is a class method that initializes a new instance from the configuration saved in the state dictionary. Adding `load_params_from_dict()` fixes the bug mentioned in #484 as it allows to load the parameters from the dict 'in-place' without initializing a new instance. This is especially important in case the optimizer is defined before loading a checkpoint (as in the qadence's `train()` function) otherwise the optimizer will point to the old model and the parameters of the newly instantiated model won't be updated.
Aside from this, I also reworked the tests so …
=> [Feature] Add in-place loading method to QuantumModel

qadence/ml_tools/config.py, qadence/ml_tools/train_grad.py, qadence/ml_tools/train_no_grad.py
This can be desired behavior in some cases, and is perhaps a better behaviour than the current where we end up raising DivideByZero errors.
We can perhaps use the `__post_int__` of the `TrainConfig` to do more validation here (like negative values), and print a warning?
Not sure what we think is best.
=> [FIX] Allow 0 to be passed as a config to print,write,plot,checkpoint_every and disable in that case

qadence/blocks/utils.py
To account for the factor 2 between the definition of TimeEvolutionBlock and usual quantum  gates, one needs to rescale the shift with the spectral gap.
=> [Bugfix] Divide shift by spectral gap for single-gap PSR

docs/tutorials/qml/ml_tools.md, pyproject.toml, qadence/ml_tools/__init__.py, qadence/ml_tools/config.py, qadence/ml_tools/data.py, qadence/ml_tools/optimize_step.py, qadence/ml_tools/train_grad.py, qadence/ml_tools/train_no_grad.py, qadence/ml_tools/utils.py
Related to a comment from #202, we can use callback functions in train functions to extend possibilities to do more during these functions and allow flexibility. Similar to scipy.optimize, we have an `OptimizeResult` class storing several optimization-related object/values.  The callback should take an `OptimizeResult` as input and apply a user-defined function.
Several booleans locate filter where the callbacks should be called within train. This also allow avoiding a few if statements for some already-defined callback-type functions (writing, checkpointing, printing, etc).
=> [Feature] Adding callback functionalities in train functions

qadence/ml_tools/config.py, qadence/ml_tools/train_grad.py, qadence/ml_tools/train_no_grad.py
For the last iteration, we impose that callbacks are run without the modulo check of `called_every`.
=> Callbacks after optimization are run without modulo check

pyproject.toml, qadence/ml_tools/saveload.py
Closes #544 
This PR corrects the `isinstance` check in `write_checkpoint` to properly detect the device, resolving the issue described in #544 .
=> [Bug] Fix `write_checkpoint` bug 

docs/tutorials/qml/ml_tools.md, qadence/ml_tools/__init__.py, qadence/ml_tools/config.py, qadence/ml_tools/train_grad.py
Simply adding an extra `modify_optimize_result` argument in `Callback` to change the `OptimizeResult` instance passed during training. A showcase is available in docs.
=> [Feature] Add possibility to modify the OptimizeResult during training in ml_tools

qadence/ml_tools/train_grad.py
Closes #559 . The writer callback would be only called during evaluation given the boolean values. So just need to separate the writer for evaluation and outside evaluation.
=> [BugFix] Fix writer callback

qadence/ml_tools/config.py, qadence/ml_tools/constructors.py
Adds a `tag` variable to the `FeatureMapConfig` and the `AnsatzConfig` dataclasses to specify their tag name. Then, in `build_qnn_from_configs()` the FM and ansatz are tagged if a tag name has been provided. 
This functionality is needed in some algorithms where certain blocks need to be identified after the QNN creation (e.g. to make them non trainable at some point)
=> [Feature] Add tagging option to QNN configs

docs/content/block_system.md, docs/tutorials/realistic_sims/noise.md, qadence/backends/pyqtorch/convert_ops.py, qadence/backends/utils.py, qadence/blocks/matrix.py, qadence/blocks/primitive.py, qadence/noise/__init__.py, qadence/noise/protocols.py, qadence/operations/control_ops.py, qadence/operations/parametric.py, qadence/operations/primitive.py, qadence/transpile/__init__.py, qadence/transpile/noise.py, qadence/types.py
Ongoing work in adding the noise from PyQ. Supersedes https://github.com/pasqal-io/qadence/pull/469.
Currently in this branch the basics should be working:
```
from qadence import NoiseType, DigitalNoise
from qadence import RX, run
noise = DigitalNoise(NoiseType.BITFLIP, error_probability = 0.2)
noise = DigitalNoise.bitflip(error_probability = 0.2) # equivalent
op = RX(0, torch.pi, noise = noise)
run(op)
---
DensityMatrix([[[0.2000+0.0000e+00j, 0.0000+3.6739e-17j],
[0.0000-3.6739e-17j, 0.8000+0.0000e+00j]]])
```
Note that currently the `DigitalNoise` is simply a name alias for the `NoiseProtocol` class directly from PyQ, which you can find here: https://github.com/pasqal-io/pyqtorch/blob/main/pyqtorch/noise/protocol.py. 
The approach in https://github.com/pasqal-io/qadence/pull/469 was …
=> [Feature] Add digital noise from PyQ

qadence/analog/device.py, qadence/blocks/abstract.py, qadence/circuit.py, qadence/execution.py, qadence/ml_tools/printing.py, qadence/parameters.py, tests/backends/horqrux/test_quantum_horqrux.py, tests/qadence/test_matrices.py
Solves #590 
Replace empty dicts default values on functions and methods calls to `None` and resolving them inside the code as `arg = arg or dict()`.
=> Fix empy dict argument default to None

qadence/measurements/shadow.py, tests/qadence/test_measurements/test_shadows.py
Solves #607 
Since we use shadows for computing expectation values only, the randomized version is just about using samples and averaging them for the case the sampled pauli-string correspond to the target pauli-string.
=> [Fix] Change shadow algorithm for using only samples

qadence/backends/pulser/backend.py, tests/conftest.py
Related to #583. Now we return single-valued expectations.
=> [Bugfix] Fix noisy simulation pulser and test

docs/content/state_init.md, qadence/backends/utils.py, qadence/states.py, qadence/utils.py, tests/backends/pyq/test_quantum_pyq.py, tests/qadence/test_states.py
=> [Feature] Add density matrix support for initial state 

docs/tutorials/qml/ml_tools/callbacks.md, docs/tutorials/qml/ml_tools/trainer.md, qadence/ml_tools/callbacks/__init__.py, qadence/ml_tools/callbacks/callback.py, qadence/ml_tools/callbacks/writer_registry.py, qadence/ml_tools/trainer.py, tests/ml_tools/test_callbacks.py
Resolves #630 
Adding additional callbacks.
- learning rate schedulers 
- early stopping 
- gradient monitering 
Additionally, writer.write method is modified to reflect more appropriate arguments.
=> [Feature] Add additional callbacks

docs/api/pasqal_cloud_connection.md, docs/tutorials/advanced_tutorials/cloud-submission.md, mkdocs.yml, pyproject.toml, qadence/pasqal_cloud_connection.py, tests/test_pasqal_cloud_connection.py
This PR aims to add features to qadence that enable the user to upload their workloads to Pasqal's cloud platform.
=> Add cloud integration features to qadence

qadence/blocks/block_to_tensor.py, qadence/mitigations/analog_zne.py, tests/qadence/test_matrices.py, tests/qadence/test_operators.py
Solves #10 . Mostly this has been solved in PyQTorch and we just set default values where it was needed.
=> [Feature] use_full_support default to False for block_to_tensor

tests/qadence/test_matrices.py, tests/qadence/test_operators.py
=> [Testing] Projector tests
