docs/qml/qaoa.md
docs/qml/qcl.md

Fixed the output of the QCL example after introducing the 2-dimensional output in the quantum model.

[Docs] Fixed and improved QCL example

---

qadence/backends/pulser/pulses.py
tests/backends/pulser_basic/test_pulser_conversion.py
tests/backends/test_pulser_pyq_compat.py

Implement local RZ gate for Pulser backend.
Closes #41

Add local RZ gate for pulser backend

---

qadence/operations.py

Fix link as suggested in #150.

Fix spurious link.

---

docs/development/draw.md
docs/qadence/draw.md
mkdocs.yml
qadence/draw/__init__.py
qadence/draw/utils.py
qadence/draw/vizbackend.py

[Fix] Display QuantumModel

---

qadence/backends/pulser/pulses.py
qadence/operations.py
tests/analog/test_pyq_vs_pulser.py
tests/backends/pulser_basic/test_rotations.py

[BugFix] Fix parameters arithmetic.

---

pyproject.toml
qadence/blocks/utils.py
qadence/circuit.py
qadence/models/quantum_model.py
tests/models/test_quantum_model.py

Include observable feature params in `model.inputs`

---

qadence/analog/parse_analog.py
qadence/backends/pulser/pulses.py
qadence/operations.py
tests/backends/pulser_basic/test_differentiation.py
tests/backends/test_gpsr.py

Partially fixes the GPSR failing tests, although an issue still persists, to be handled by https://github.com/pasqal-io/qadence/issues/266

[BugFix] failing GPSR fix

---

docs/advanced_tutorials/index.md
docs/advanced_tutorials/projectors.md
mkdocs.yml

Add missing doc section for the projector blocks.

[Docs] Add projector docs

---

docs/realistic_sims/mitigation.md
docs/realistic_sims/noise.md

[Docs] Add mitigation docs

---

docs/realistic_sims/measurements.md

[Docs] Add docs measurements

---

docs/qml/qml_constructors.md
qadence/constructors/feature_maps.py
qadence/constructors/rydberg_feature_maps.py
tests/constructors/test_feature_maps.py

[Feature] Add trainable frequency feature maps

---

qadence/constructors/iia.py
tests/constructors/test_ansatz.py

Closes #288
Added SDAQC strategy to IIA just like how it is for HEA.
Introduced changes:
- Added an argument `strategy` in the function to get identity initialized ansatz. It defaults to fully digital, thus not breaking any existing code.
- Changed the default value of the `entangler` to `None` from `CNOT` to take into account the digital-analog paradigm. For digital, it still defaults to `CNOT` thus not breaking any existing code. Defaults to NN interaction for digital-analog.
- Added CPHASE to the list of possible 2 qubit digital entangling gates.
- Some minor docstring changes.
- Added tests for the IIA with SDAQC strategy.

[Feature] Added SDAQC strategy for IIA

---

pyproject.toml
qadence/backends/pyqtorch/backend.py
qadence/backends/pyqtorch/convert_ops.py
qadence/ml_tools/models.py
qadence/models/quantum_model.py

Bugfix depending on https://github.com/pasqal-io/pyqtorch/pull/135
1. Custom 'to' device method for QuantumModel and TransformedModule
2. Fix bug in PyQ diagonal observable where register was not moved to device
3. Add logging to QuantumModel and TransformedModule

[Fix] Correctly move models to GPU

---

pyproject.toml
qadence/protocols.py

[Feature] Add protocols extras

---

examples/backends/low_level/horqrux_analog.py
pyproject.toml
qadence/backends/horqrux/backend.py
qadence/backends/horqrux/config.py
qadence/backends/horqrux/convert_ops.py
qadence/backends/jax_utils.py
qadence/backends/utils.py
qadence/blocks/__init__.py
qadence/execution.py
qadence/utils.py
tests/backends/test_backends.py
tests/backends/test_endianness.py

[Feature] Add JAX / Horqrux HamiltonianEvolution

---

qadence/backends/pyqtorch/backend.py
qadence/engines/torch/differentiable_expectation.py

- Move no_grad call  to backend pyq level
- Remove dead code from engine introduction

[Refac] Torch sample as no_grad

---

pyproject.toml

To avoid failures in other PRs, namely #373.

Pin Braket version.

---

README.md
pyproject.toml
qadence/libs.py

Integrate `qadence-libs` to extras.

Add libs to extras.

---

pyproject.toml
qadence/ml_tools/models.py
qadence/ml_tools/train_grad.py
qadence/models/quantum_model.py
tests/ml_tools/test_train.py
tests/ml_tools/test_transformed_module.py

Until #385 is finalized, we need to fix the currently broken `to` method of the current TransformedModule

[Fix] Correctly set precision in torch TransformedModule

---

qadence/models/quantum_model.py

[Refactor] Remove setting noise model in sample call.

---

qadence/backends/pulser/backend.py

[Bug] Correct SimConfig syntax.

---

pyproject.toml
renovate.json

[Infra] Fix Renovate config

---

pyproject.toml
renovate.json

Better Renovate config syntax.

[Infra] More fixes renovate config

---

qadence/backends/gpsr.py
tests/backends/test_gpsr.py

Originally this MR was related to https://github.com/pasqal-io/qadence/issues/397
Decided to simplify it since properly making all other changes caused other issues.

[Bug] Partially fix GPSR for HamEvo

---

qadence/types.py
tests/qadence/test_parameters.py

fixes https://github.com/pasqal-io/qadence/issues/422

[Fix] Allow numpy numeric types in Parameters

---

pyproject.toml

Bump version.

---

pyproject.toml
qadence/ml_tools/saveload.py
qadence/parameters.py
qadence/states.py

Fixes https://github.com/pasqal-io/qadence/issues/463

[Fix] Remove jax import in `states` module

---

README.md

[Documentation] Add WSL and Windows instructions

---

pyproject.toml
qadence/blocks/matrix.py

[Docs] Fix pipeline

---

qadence/extensions.py

Fix failing backend import when in extensions. Should fix the failing CI in extensions.

[Bug] Fix backend import if in extensions.

---

docs/tutorials/qml/ml_tools.md
qadence/ml_tools/train_grad.py

[Feature] Allow loss_fn in train_grad to return arbitrary number of values.

---

qadence/ml_tools/train_grad.py

[Bug] Fix printing format error in train_grad

---

.github/dependabot.yml
.github/workflows/dependabot.yml
pyproject.toml

Remove deadcode and useless files.

[Refactor] Minor code base clean-up

---

qadence/ml_tools/config.py
qadence/ml_tools/printing.py
tests/ml_tools/test_logging.py

[Bug] Fix MLFlow import, and setup function that caused tests to fail

---

qadence/backend.py
qadence/backends/braket/backend.py
qadence/backends/horqrux/backend.py
qadence/backends/pulser/backend.py
qadence/backends/pyqtorch/backend.py
qadence/mitigations/analog_zne.py

I will progressively work on some things towards adding the PyQ noise to Qadence. Some of it is already done in https://github.com/pasqal-io/qadence/pull/469, but I think I will separate it in a few MRs.

[Refact] Some qadence noise / pulser backend changes

---

qadence/measurements/utils.py
tests/qadence/test_measurements/test_tomography.py

Solves #603 and also adds the extra test to reflect the change.

[Bugfix] Fix rotations in tomography

---

qadence/backends/pyqtorch/backend.py
qadence/backends/pyqtorch/config.py
qadence/types.py
tests/backends/pyq/test_quantum_pyq.py

[Feature] Add quantum dropout 

---

docs/getting_started/installation.md

[Docs] Update docs on OS and WLS2 use.

---

qadence/ml_tools/config.py
qadence/ml_tools/constructors.py
qadence/types.py
tests/ml_tools/test_qnn.py

Add config constructor to use QNN with ALA ansatz

---

qadence/utils.py

Closes #663 
Remove additional run() calls by deleting `P0_MATRIX` and `P1_MATRIX`

[Refactor] Remove additional run() calls when importing qadence

---

qadence/blocks/block_to_tensor.py
tests/qadence/test_matrices.py

[Feature] Add parametric blocks support for block_to_diagonal

---

qadence/register.py

[Bug] Fix `networkx` deprecation warning 

---

qadence/ml_tools/callbacks/callbackmanager.py

[Refactoring] Disable save checkpoint when checkpoint_every==0

---

qadence/utils.py
tests/test_str_utils.py

[Bugfix] Fix `block_to_mathematical_expression` when block is multiplied by parameter

---

pyproject.toml

[Update] Pyqtorch to 1.7.6 and Horqrux to 0.8.1

---

pyproject.toml

Updating pyproject to add qadence-hub packages installation

add qadence hub packages

---

qadence/model.py
qadence/transpile/__init__.py
qadence/transpile/block.py
tests/backends/pyq/test_quantum_pyq.py
tests/backends/test_backends.py
tests/qadence/test_blocks.py
tests/qadence/test_quantum_model.py

[Refactor] set_trainable refactoring

---

qadence/states.py
tests/qadence/test_states.py

[Feature] Density matrix utility functions

---

pyproject.toml
qadence/ml_tools/tensors.py
qadence/ml_tools/trainer.py

Copy of this [PR](https://github.com/pasqal-io/perceptrain/pull/23) in Perceptrain, which at least partially solves this [issue](https://github.com/pasqal-io/perceptrain/issues/22)

 [Bug] Don't track gradients in the loss/metric history

---

renovate.json

Quick reviewers update for Renovate bot.

[Infra] Update Renovate config.
